site_name: STAG dokumentace
repo_url: https://github.com/mfvs
repo_name: MFVS/org


theme:
  icon:
      repo: fontawesome/brands/github-alt
  favicon: images/favicon.png
  name: material
  palette:
    primary: blue-grey
    accent: deep orange
  logo: assets/ujep-logo.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Úvod: index.md
  - Jak používat webové služby: ws-guide.md