site_name: STAG - Návody a dokumentace
repo_url: https://github.com/mfvs
repo_name: MFVS/org

markdown_extensions:
  - toc:
      title: Obsah
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  features:
      - navigation.tabs
      - content.code.copy
      - content.code.annotate
      - navigation.top
      - navigation.indexes
      - navigation.expand
  icon:
    repo: fontawesome/brands/github
  favicon: assets/none.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: black
      accent: purple

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: black
      accent: purple
  logo: assets/ujep_logo.svg
extra_css:
  - stylesheets/extra.css

plugins:
  - search # search plugin musi byt specifikova. glightbox vypina
  - glightbox


nav:
  - Popis: index.md
  - Návody:
      - guide/index.md
      - Webové služby STAG: 
        - Request bez přihlášení: guide/ws/requests_nolog.md
        - Request s přihlášením: guide/ws/requests_log.md
      - Aplikace:
        - Přihlašování přes STAG:
          - Dokumentace: guide/apps/login.md
          - Streamlit: guide/apps/st_login.md
          - Shiny: guide/apps/shiny_login.md
  - Projekty:
      - projects/index.md
      - Erasmus: projects/erasmus.md
      - Výkazy: projects/vykazy.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yoptohlejepeta
      name: yoptohlejepeta