site_name: STAG Projekty — Návody a dokumentace
repo_url: https://github.com/mfvs
repo_name: MFVS/org

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

theme:
  features:
      - navigation.tabs
      - content.code.copy
      - content.code.annotate
  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle 
  favicon: assets/favicon.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
      primary: blue-grey
      accent: deep-orange

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: blue-grey
      accent: deep-orange
  logo: assets/ujep_logo.svg

plugins:
  - search # search plugin musi byt specifikova. glightbox vypina
  - glightbox


nav:
  - Popis: index.md
  - Návody:
      - Úvod: guide/index.md
      - Webové služby STAG: guide/ws.md
      - Aplikace — přihlašování přes STAG: guide/login.md
  - Projekty:
      - Úvod: projects/index.md
      - Erasmus: projects/erasmus.md
      - Výkazy: projects/vykazy.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/yoptohlejepeta
      name: yoptohlejepeta
    - icon: fontawesome/brands/discord
      link: https://discordapp.com/users/267984510166106113
      name: El Pedro